l18n to Portuguese (Brazil)
Project-OSRM/osrm-frontend pull request #288
Opened 2018-09-18 01:42 UTC by jppcel

2018-09-18 18:47 UTC, yuryleb requested changes
Also it's necessary to update `src/localization.js` to explicitly load your localization file.

2018-09-18 18:47 UTC, yuryleb commented on i18n/pt-br.js
> +  key: 'pt-br',
Maybe it's better to use 'pt-BR' key to exactly match osrm-text-instructions' language pack name?

2018-09-18 19:40 UTC, jppcel commented
done.

2018-09-18 20:57 UTC, yuryleb approved these changes
Thanks!

2019-03-06 11:44 UTC, merged

2019-03-10 07:03 UTC, bbridges commented
I'm not able to start the `osrm/osrm-frontend` container from this PR since the filename used in `src/localization.js` was assuming the path was case-insensitive.

I get a build error with:
```text
> browserify -d src/index.js -s osrm > bundle.raw.js && uglifyjs bundle.raw.js -c -m --source-map=bundle.js.map -o bundle.js

Error: Cannot find module '../i18n/pt-BR' from '/src/src'
```

It runs fine with `'../i18n/pt-br'`, though.

2019-03-11 12:29 UTC, freenerd commented
@bbridges should be fixed via #298